export const START_DOWNLOAD_COUNTRIES =  'START_DOWNLOAD_COUNTRIES';
export const DOWNLOAD_COUNTRIES_SUCCESS =   'DOWNLOAD_COUNTRIES_SUCCESS';
export const DOWNLOAD_COUNTRIES_ERROR = 'DOWNLOAD_COUNTRIES_ERROR';